AMC Banking Fundamentals 365 V21.5 HF1
microsoft/ALAppExtensions pull request #22735
Opened 2023-03-28 14:10 UTC by AMCNV

Please hotfix into 21.5

2023-04-11 13:23 UTC, AMCJN submitted a review, later dismissed

2023-05-01 14:48 UTC, AMCNV commented
Hi @haoranpb @JesperSchulz 
I'm tagging you since you were involved in reviewing our last pull request.

It's been a month since we made the pull request and we don't have an assignee yet.
Are we missing anything on our side or are you simply busy? If it is the first please let us know.
If it is the latter, could you give us an estimate of when you will have time to review it?

Best Regards
NIels Voetmann
AMC Consult

2023-05-08 08:29 UTC, haoranpb commented
I guess this is the follow up from #21879, the previous one was only ported to master, is this also only needed in master branch?

@amcnv @AMCJN

2023-05-08 08:40 UTC, haoranpb requested changes
Some small changes

2023-05-08 08:40 UTC, haoranpb commented on Apps/W1/AMCBanking365Fundamentals/app/Codeunits/AMCBankAssistedMgt.Codeunit.al
> +        AMCBoughtModule: Boolean;
we usually initialize the variables, even if we want the default value

2023-05-08 08:40 UTC, haoranpb commented on Apps/W1/AMCBanking365Fundamentals/app/Codeunits/AMCBankAssistedMgt.Codeunit.al
> +            (not AMCBankingMgt.IsLicenseEqualAMC) and
this is a procedure? If so `IsLicenseEqualAMC()`

2023-05-08 08:40 UTC, haoranpb commented on Apps/W1/AMCBanking365Fundamentals/app/Codeunits/AMCBankingMgt.Codeunit.al
> +    [NonDebuggable]
Do we need this? since it's hardcoded here anyway

2023-05-08 08:40 UTC, haoranpb commented on Apps/W1/AMCBanking365Fundamentals/app/Codeunits/AMCBankingMgt.Codeunit.al
> +    var
do we need this?

2023-05-08 08:40 UTC, haoranpb commented on Apps/W1/AMCBanking365Fundamentals/app/Pages/AMCBankBankAccountCard.PageExt.al
> +    var
Do we need this?

2023-05-08 08:40 UTC, haoranpb commented on Apps/W1/AMCBanking365Fundamentals/app/Pages/AMCBankBankAccountCard.PageExt.al
> +    var
Same for other procedure definitions

2023-05-08 08:40 UTC, haoranpb commented on Apps/W1/AMCBanking365Fundamentals/test/src/Libraries/LibraryAMCWebService.Codeunit.al
> +    [Scope('OnPrem')]
is this needed?

2023-05-08 08:40 UTC, haoranpb commented on Apps/W1/AMCBanking365Fundamentals/test/src/Libraries/LibraryAMCWebService.Codeunit.al
> +    procedure SetHttpClientRequestallowed()
can we internal this?

2023-05-08 08:40 UTC, haoranpb commented on Apps/W1/AMCBanking365Fundamentals/app/Codeunits/AMCBankAssistedMgt.Codeunit.al
> +        AMCBoughtModule: Boolean;
Same for other variable definitions

2023-05-08 09:50 UTC, haoranpb commented on Apps/W1/AMCBanking365Fundamentals/app/Codeunits/AMCBankAssistedMgt.Codeunit.al
> +        AMCBoughtModule: Boolean;
nvm, realized you are assigning it before use

2023-05-10 08:30 UTC, AMCNV commented on Apps/W1/AMCBanking365Fundamentals/app/Pages/AMCBankBankAccountCard.PageExt.al
> +    var
Yes it is needed.

2023-05-10 08:31 UTC, AMCNV commented on Apps/W1/AMCBanking365Fundamentals/app/Codeunits/AMCBankingMgt.Codeunit.al
> +    var
no we don't.

2023-05-10 09:09 UTC, AMCNV commented
Hi Haoran, thank you for the response! 😄 
It does not seem that I have permission to assign or change assignees, so my only option was to tag you.
I also do not receive notifications when you comment.

I have now looked at your review and made necessary changes.
Let me know if there still are some unresolved issues.

Yes the change is a follow up. We would like these changes to be reflected as soon as possible, as they fix bugs that occurred in our app after Microsoft changed the method SetBatchFilters() of Record "Gen. Journal Line" of table 1228.

@haoranpb

2023-05-10 12:40 UTC, haoranpb commented
@AMCNV tagging me would work as well 😄 

I have ported the changes to internal system, will ask my colleagues to do another round of review.

Will keep you posted for the process

2023-05-12 06:20 UTC, JesperSchulz commented
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 10776.

2023-05-12 06:20 UTC, closed without merging

2023-05-12 11:19 UTC, haoranpb commented
@AMCNV @AMCJN  the code is merged in master, I'm porting down the change along with #21879 to 22.x at the moment

I'd expect it to be available from 22.x

2023-05-15 10:55 UTC, haoranpb commented
Merged into 22.x