Update ConnectivityAppDefinitions.Codeunit.al
microsoft/ALAppExtensions pull request #22955
Opened 2023-04-11 11:28 UTC by lukasaus

Softera.Bankfeed added

2023-04-17 10:56 UTC, sorenfriisalexandersen requested changes

2023-04-17 10:56 UTC, sorenfriisalexandersen commented on Apps/W1/ConnectivityApps/app/src/Codeunits/ConnectivityAppDefinitions.Codeunit.al
> +        AppProviderSupportURL := 'https://www.softera.lt/en/banking-automation-payment-management-bankfeed/';
@lukasaus The link to supported banks should go directly to the place where the user can see which banks are supported. I suggest you change it to this one: https://www.softera.lt/en/supported-banks-softera-bankfeed/

2023-04-24 12:37 UTC, sorenfriisalexandersen approved these changes

2023-04-25 06:53 UTC, merged

2023-04-25 06:54 UTC, JesperSchulz commented
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 10575.