GP Updates - September 2024
microsoft/ALAppExtensions pull request #27265
Opened 2024-09-16 14:17 UTC by jaymckinney-enavate

This PR contains the following enhancements to the GP migrations.

- Hide the Run Data Upgrade Now action when the One Step Migration is enabled.
- Remove the dependency on Sales and Inventory Forecast app.
- Obsolete the old GP pages around the staging table data.

2024-09-19 13:52 UTC, nikolakukrika requested changes
We cannot remove the staging tables as they are still actively used. The rest of the changes are fine

2024-09-19 13:52 UTC, nikolakukrika commented on Apps/W1/HybridGP/app/Permissions/HybridGPObjects.PermissionSet.al
> +                    page "GP Customer" = X,
I think we still need the GP Customers, Vendors and Items, right?

2024-09-30 09:46 UTC, merged

2024-09-30 20:34 UTC, JesperSchulz commented
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 24886.

2024-11-08 12:30 UTC, JesperSchulz commented
Availability update: We will publish a fix for this issue in the next update for release 25.

Build ID to track: 26506.